// <auto-generated />
using System;
using Arch.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Arch.Infra.Data.Migrations
{
    [DbContext(typeof(EventSourcingCoreContext))]
    [Migration("20200112204144_InitEventSourcing")]
    partial class InitEventSourcing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Arch.Domain.Core.Event.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<Guid>("AggregateId");

                    b.Property<string>("Assembly");

                    b.Property<string>("Data");

                    b.Property<string>("User");

                    b.Property<string>("When");

                    b.Property<string>("Who");

                    b.HasKey("Id");

                    b.ToTable("StoredEvent");
                });

            modelBuilder.Entity("Arch.Infra.Shared.EventSourcing.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<Guid>("AggregateId");

                    b.Property<string>("Assembly");

                    b.Property<string>("Data");

                    b.Property<string>("When");

                    b.Property<string>("Who");

                    b.HasKey("Id");

                    b.ToTable("EventEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
